// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginOperation() {
  return window['go']['app']['App']['BeginOperation']();
}

export function Bootstrap() {
  return window['go']['app']['App']['Bootstrap']();
}

export function CalculateChecksum(arg1, arg2) {
  return window['go']['app']['App']['CalculateChecksum'](arg1, arg2);
}

export function CancelOperation(arg1) {
  return window['go']['app']['App']['CancelOperation'](arg1);
}

export function DetectDuplicates(arg1, arg2) {
  return window['go']['app']['App']['DetectDuplicates'](arg1, arg2);
}

export function ExportImages(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportImages'](arg1, arg2, arg3);
}

export function FinishOperation(arg1) {
  return window['go']['app']['App']['FinishOperation'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function LoadDocumentByPath(arg1) {
  return window['go']['app']['App']['LoadDocumentByPath'](arg1);
}

export function LoadImage(arg1) {
  return window['go']['app']['App']['LoadImage'](arg1);
}

export function LoadImageByPath(arg1) {
  return window['go']['app']['App']['LoadImageByPath'](arg1);
}

export function LoadImageByPathWithOperation(arg1, arg2) {
  return window['go']['app']['App']['LoadImageByPathWithOperation'](arg1, arg2);
}

export function LoadLibraryCache(arg1) {
  return window['go']['app']['App']['LoadLibraryCache'](arg1);
}

export function PrepareMediaByPath(arg1) {
  return window['go']['app']['App']['PrepareMediaByPath'](arg1);
}

export function LoadThumbnailByPath(arg1, arg2) {
  return window['go']['app']['App']['LoadThumbnailByPath'](arg1, arg2);
}

export function ResetLibrary() {
  return window['go']['app']['App']['ResetLibrary']();
}

export function SaveLibraryCache(arg1, arg2) {
  return window['go']['app']['App']['SaveLibraryCache'](arg1, arg2);
}

export function ScanDirectory(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ScanDirectory'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectDirectory(arg1) {
  return window['go']['app']['App']['SelectDirectory'](arg1);
}
