// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function BeginOperation():Promise<number>;

export function Bootstrap():Promise<app.BootstrapPayload>;

export function CalculateChecksum(arg1:app.ImageEntry,arg2:number):Promise<string>;

export function CancelDownload(arg1:string):Promise<void>;

export function CancelOperation(arg1:number):Promise<void>;

export function DetectDuplicates(arg1:Array<app.ImageEntry>,arg2:number):Promise<Array<app.DuplicateGroup>>;

export function ExportImages(arg1:Array<app.ImageEntry>,arg2:string,arg3:number):Promise<app.ExportResult>;

export function FinishOperation(arg1:number):Promise<void>;

export function GetAppInfo():Promise<app.AppInfo>;

export function ListDownloads():Promise<Array<app.DownloadItem>>;

export function LoadDocumentByPath(arg1:string):Promise<app.DocumentPayload>;

export function LoadImage(arg1:string):Promise<app.ImagePayload>;

export function LoadImageByPath(arg1:string):Promise<app.ImagePayload>;

export function LoadImageByPathWithOperation(arg1:string,arg2:number):Promise<app.ImagePayload>;

export function LoadLibraryCache(arg1:string):Promise<string>;

export function LoadThumbnailByPath(arg1:string,arg2:number):Promise<app.ImagePayload>;

export function OpenDownloadsDirectory():Promise<void>;

export function PrepareCompatibleMediaByPath(arg1:string):Promise<string>;

export function PrepareMediaByPath(arg1:string):Promise<string>;

export function RemoveDownload(arg1:string):Promise<void>;

export function ResetLibrary():Promise<void>;

export function ResolveDownloadURL(arg1:string):Promise<app.DownloadResolution>;

export function RevealDownload(arg1:string):Promise<void>;

export function SaveLibraryCache(arg1:string,arg2:string):Promise<void>;

export function ScanDirectory(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:Array<string>,arg5:number):Promise<app.DirectoryScanResult>;

export function SelectDirectory(arg1:string):Promise<string>;

export function StartDownload(arg1:string):Promise<app.DownloadItem>;

export function StartResolvedDownload(arg1:string,arg2:string,arg3:string):Promise<app.DownloadItem>;
