// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['app']['DownloadService']['CancelDownload'](arg1);
}

export function ListDownloads() {
  return window['go']['app']['DownloadService']['ListDownloads']();
}

export function OpenDownloadsDirectory() {
  return window['go']['app']['DownloadService']['OpenDownloadsDirectory']();
}

export function RemoveDownload(arg1) {
  return window['go']['app']['DownloadService']['RemoveDownload'](arg1);
}

export function ResolveDownloadURL(arg1) {
  return window['go']['app']['DownloadService']['ResolveDownloadURL'](arg1);
}

export function RevealDownload(arg1) {
  return window['go']['app']['DownloadService']['RevealDownload'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['app']['DownloadService']['StartDownload'](arg1);
}

export function StartResolvedDownload(arg1, arg2, arg3) {
  return window['go']['app']['DownloadService']['StartResolvedDownload'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['app']['DownloadService']['Startup'](arg1);
}
