// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function ListDownloads():Promise<Array<app.DownloadItem>>;

export function OpenDownloadsDirectory():Promise<void>;

export function RemoveDownload(arg1:string):Promise<void>;

export function ResolveDownloadURL(arg1:string):Promise<app.DownloadResolution>;

export function RevealDownload(arg1:string):Promise<void>;

export function StartDownload(arg1:string):Promise<app.DownloadItem>;

export function StartResolvedDownload(arg1:string,arg2:string,arg3:string):Promise<app.DownloadItem>;

export function Startup(arg1:context.Context):Promise<void>;
