// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmTrashEntries(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['FileService']['ConfirmTrashEntries'](arg1, arg2, arg3, arg4, arg5);
}

export function MoveEntries(arg1, arg2) {
  return window['go']['app']['FileService']['MoveEntries'](arg1, arg2);
}

export function RenameEntry(arg1, arg2) {
  return window['go']['app']['FileService']['RenameEntry'](arg1, arg2);
}

export function SelectMoveDestination(arg1) {
  return window['go']['app']['FileService']['SelectMoveDestination'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['FileService']['Startup'](arg1);
}

export function TrashEntries(arg1) {
  return window['go']['app']['FileService']['TrashEntries'](arg1);
}
