// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function ConfirmTrashEntries(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:string):Promise<app.TrashResult>;

export function MoveEntries(arg1:Array<string>,arg2:string):Promise<app.MoveResult>;

export function RenameEntry(arg1:string,arg2:string):Promise<app.ImageEntry>;

export function SelectMoveDestination(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function TrashEntries(arg1:Array<string>):Promise<app.TrashResult>;
