// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function PrepareCompatibleMediaByPath(arg1:string,arg2:number):Promise<string>;

export function PrepareDocumentByPath(arg1:string,arg2:number):Promise<string>;

export function PrepareMediaByPath(arg1:string,arg2:number):Promise<string>;

export function ReleasePlaybackCache(arg1:string):Promise<void>;

export function ReplaceRemuxedOriginal(arg1:string):Promise<app.ImageEntry>;

export function Startup(arg1:context.Context):Promise<void>;
