// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PrepareCompatibleMediaByPath(arg1, arg2) {
  return window['go']['app']['MediaService']['PrepareCompatibleMediaByPath'](arg1, arg2);
}

export function PrepareDocumentByPath(arg1, arg2) {
  return window['go']['app']['MediaService']['PrepareDocumentByPath'](arg1, arg2);
}

export function PrepareMediaByPath(arg1, arg2) {
  return window['go']['app']['MediaService']['PrepareMediaByPath'](arg1, arg2);
}

export function ReleasePlaybackCache(arg1) {
  return window['go']['app']['MediaService']['ReleasePlaybackCache'](arg1);
}

export function ReplaceRemuxedOriginal(arg1) {
  return window['go']['app']['MediaService']['ReplaceRemuxedOriginal'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['MediaService']['Startup'](arg1);
}
