// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelUpdate() {
  return window['go']['app']['UpdateService']['CancelUpdate']();
}

export function CheckForUpdates() {
  return window['go']['app']['UpdateService']['CheckForUpdates']();
}

export function FrontendReady() {
  return window['go']['app']['UpdateService']['FrontendReady']();
}

export function GetUpdateProgress() {
  return window['go']['app']['UpdateService']['GetUpdateProgress']();
}

export function GetUpdateState() {
  return window['go']['app']['UpdateService']['GetUpdateState']();
}

export function InstallUpdate(arg1) {
  return window['go']['app']['UpdateService']['InstallUpdate'](arg1);
}
