// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CancelUpdate():Promise<app.UpdateState>;

export function CheckForUpdates():Promise<app.UpdateState>;

export function FrontendReady():Promise<void>;

export function GetUpdateProgress():Promise<app.UpdateProgress>;

export function GetUpdateState():Promise<app.UpdateState>;

export function InstallUpdate(arg1:string):Promise<app.UpdateState>;
